# Generated by Django 3.1.6 on 2021-02-08 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField()),
                ('miniapp_user_token', models.TextField(blank=True, null=True)),
                ('cost', models.IntegerField()),
                ('purchase_details_url', models.URLField(blank=True, null=True)),
                ('voucher_url', models.URLField(blank=True, null=True)),
                ('terminal_id', models.TextField()),
                ('purchase_description', models.TextField()),
                ('purchase_items', models.JSONField(default=dict)),
                ('user_ip_address', models.GenericIPAddressField()),
                ('merchant_user_id', models.TextField(blank=True, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('tpaga_payment_url', models.URLField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('cancelled_at', models.TextField(blank=True, null=True)),
                ('checked_by_merchant_at', models.TextField(blank=True, null=True)),
                ('delivery_notification_at', models.TextField(blank=True, null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dishes.dish')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
